import Head from 'next/head'
import { Inter } from '@next/font/google'
import ScrollToTop from '@/components/ScrollToTop'
import Navbar from '@/components/Navbar'
import SectionHome from '@/components/SectionHome'
import SectionAbout from '@/components/SectionAbout'
import SectionTeam from '@/components/SectionTeam'
import SectionSkills from '@/components/SectionSkills'
import SectionContact from '@/components/sectionContact'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SaradONGa | ISPP 12</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      </Head>

      <ScrollToTop/>

      <Navbar/>

      <SectionHome/>
      <SectionAbout/>
      <SectionTeam/>
      <SectionSkills/>
      <SectionContact/>
      <Footer/>

{/* TODO: REMOVE */}

      {/* <!-- JQuery --> */}
      <script src="/vendors/jquery/jquery-3.6.0.js"></script>

      {/* <!-- SWIPER JS --> */}
      <script src="/vendors/swiper/swiper.js"></script>

      {/* <!-- Magnific-Popup JS --> */}
      <script src="/vendors/magnific-popup/jquery.magnific-popup.js"></script>

      {/* <!-- Typed JS --> */}
      <script src="/vendors/typed/typed.js"></script>

      {/* <!-- Custom Script File --> */}
      <script src="/js/script.js"></script>
      <script src="/js/scroll-spy.js"></script>
      <script src="/js/counter-up.js"></script>
      <script src="/js/portfolio.js"></script>
      <script src="/js/testi-slider.js"></script>
      <script src="/js/blog-slider.js"></script>
      <script src="/js/typed.js"></script>
      <script src="/js/contact.js"></script>

    </>
  )
}
