import Head from 'next/head'
import { Inter } from '@next/font/google'
import ScrollToTop from '@/components/ScrollToTop'
import Navbar from '@/components/Navbar'
import SectionHome from '@/components/SectionHome'
import SectionAbout from '@/components/SectionAbout'
import SectionTeam from '@/components/SectionTeam'
import SectionSkills from '@/components/SectionSkills'
import SectionContact from '@/components/sectionContact'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SaradONGa | ISPP 12</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <ScrollToTop/>

      <Navbar/>

      <SectionHome/>
      <SectionAbout/>
      <SectionTeam/>
      <SectionSkills/>
      <SectionContact/>
      <Footer/>

{/* TODO: REMOVE */}

      {/* <!-- JQuery --> */}
      <script src="/vendors/jquery/jquery-3.6.0.js"></script>

      {/* Not used */}
      {/* <!-- SWIPER JS --> */}
      {/* <script src="/vendors/swiper/swiper.js"></script> */}

      {/* <!-- Magnific-Popup JS --> */}
      <script src="/vendors/magnific-popup/jquery.magnific-popup.js"></script>

      {/* <!-- Typed JS --> */}
      <script src="/vendors/typed/typed.js"></script>


      {/* <!-- Custom Script File --> */}
      <script src="/utils/script.js"></script>
      <script src="/utils/scroll-spy.js"></script>
      <script src="/utils/portfolio.js"></script>
      <script src="/utils/contact.js"></script>
      {/* <script src="/utils/counter-up.js"></script> */}
      {/* <script src="/utils/typed.js"></script> */}

      {/* Not used */}
      {/* <script src="/utils/blog-slider.js"></script> */}
      {/* <script src="/utils/testi-slider.js"></script> */}
    </>
  )
}
